name: Check compilation and tests

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Compil:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    name: compil
    steps:
      - uses: actions/checkout@v2
      - run: make fclean
      - run: make
